config register respone & delete type in kahoot
LQuangTien/kahoot-clone-server pull request #10
Opened 2020-09-18 15:08 UTC by LQuangTien

2020-09-18 15:13 UTC, tranthaison1231 requested changes

2020-09-18 15:13 UTC, tranthaison1231 commented on src/modules/Auth/auth.controller.ts
> +      password + '',
Sao lại password + '' e hì, password không được à

2020-09-18 15:13 UTC, tranthaison1231 commented on src/modules/Kahoot/kahoot.controller.ts
>      const newKahoot = await this.kahoot.findOneAndUpdate(
Tìm hiểu lean mongoose nhé.

2020-09-18 15:13 UTC, tranthaison1231 commented on src/modules/Kahoot/kahoot.controller.ts
>      const kahoot = await this.kahoot.findByIdAndDelete(id);
Tìm hiểu lean mongoose nhé. Nhớ .lean

2020-09-20 01:39 UTC, tranthaison1231 commented on src/modules/Question/question.model.ts
> +    get: toObjectId
Get ni là chi ri Tiến hì.

2020-09-20 01:39 UTC, tranthaison1231 commented on src/modules/Kahoot/kahoot.controller.ts
> +import kahootModel from './kahoot.model';
Sửa lại cho a kahootModel -> KahootModel. Đổi toàn bộ Model theo tên như rứa nha

2020-09-20 05:10 UTC, LQuangTien commented on src/modules/Kahoot/kahoot.model.ts
> +      default: []
bỏ default, sai rồi

2020-09-20 06:32 UTC, tranthaison1231 approved these changes

2020-09-20 06:32 UTC, merged